//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmvDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master
    {
        public string ActionID { get; set; }
        public string TaskID { get; set; }
        public string ActionName { get; set; }
        public string Success { get; set; }
    }
}
