//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmvDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public string SessionID { get; set; }
        public string StartTimestamp { get; set; }
        public string EndTimestamp { get; set; }
        public string User { get; set; }
    }
}
