//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmvDb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SMVEntities : DbContext
    {
        public SMVEntities()
            : base("name=SMVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Master> Masters { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<Plugin> Plugins { get; set; }
        public virtual DbSet<SessionTaskMapping> SessionTaskMappings { get; set; }
        public virtual DbSet<SessionTimestampMapping> SessionTimestampMappings { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TaskErrorLogMapping> TaskErrorLogMappings { get; set; }
        public virtual DbSet<TaskModuleMapping> TaskModuleMappings { get; set; }
        public virtual DbSet<TaskPluginMapping> TaskPluginMappings { get; set; }
    }
}
