//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmvDb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmvDbEntities : DbContext
    {
        public SmvDbEntities()
            : base("name=SmvDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<Plugin> Plugins { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<SessionTask> SessionTasks { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TaskAction> TaskActions { get; set; }
        public virtual DbSet<TaskModule> TaskModules { get; set; }
        public virtual DbSet<TaskPlugin> TaskPlugins { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
    }
}
