//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmvDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public string TaskID { get; set; }
        public string Log { get; set; }
        public string Command { get; set; }
        public string Arguments { get; set; }
        public string Bugs { get; set; }
    }
}
